# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
  port: 80
spring:
  redis:
    database: 0
    host: localhost
    port: 6379
# 是否开启redis缓存  true开启   false关闭
sys:
  redis:
    open: true