server:
  port: 8080

spring:
  application:
    name: nacos-demo # nacos服务名

# ======================== ↓↓↓↓↓↓ nacos相关配置 ↓↓↓↓↓↓ ===============================
nacos:
  # 配置管理
  config:
    server-addr: 127.0.0.1:8848 # TODO 这里换成自己的ip加端口
  # 服务注册与发现
  discovery:
    server-addr: ${nacos.config.server-addr}