server:
  port: 81

#配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot_hello?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: Ray@1998
    password: root
knife4j:
  enable: true